server:
  port: 8080
  tomcat:
    uriEncoding: UTF-8

################################  log  ##################################
logging:
  level:
    root: info
#########################################################################
